receivers:
  otlp:
    protocols:
      # http:
      #   endpoint: "0.0.0.0:4318"
      #   cors:
      #     allowed_origins: ["*"]
      #     allowed_headers: ["*"]
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  debug:
    verbosity: detailed

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
