services:
  collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:latest
    command: ["--config=/otel-collector-config.yaml"]
    volumes:
      - './config.yaml:/otel-collector-config.yaml:z'
    ports:
      - "4317:4317"
